spring:

  application:
    name: "backend"

  datasource:
    url: "jdbc:postgresql://${DB_HOST}:5432/tingeso"
    username: "postgres"
    password: "postgres"
    # PROD
    # url: "${SPRING_DATASOURCE_URL}"
    # username: "${SPRING_DATASOURCE_USERNAME}"
    # password: "${SPRING_DATASOURCE_PASSWORD}"

    jpa:
      show-sql: true
      # defer-datasource-initialization: true
      properties:
        hibernate:
          dialect: "org.hibernate.dialect.PostgreSQLDialect"
          ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      open-in-view: true

# DEBUG
# h2:
#  console:
#    enabled: true

server:
    port: 8090
